apiVersion: 1

datasources:
  - id: 1
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: "/public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    access: proxy
    url: http://prometheus:9090
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: POST
    readOnly: false